//
//  AppData.swift
//  Verification_APP
//
//  Created by m on 11/24/18.
//  Copyright © 2018 WzyoU. All rights reserved.
//

import Foundation
struct cuntries {
    
    static var cuntry_name = ["Afghanistan",
                              "Albania",
                              "Algeria",
                             
                              "Andorra",
                              "Angola",
                              "Anguilla",
                              "Antarctica",
                           
                              "Argentina",
                              "Armenia",
                              "Aruba",
                              "Australia",
                              "Austria",
                              "Azerbaijan",
                              "Bahamas",
                              "Bahrain",
                              "Bangladesh",
                              "Barbados",
                              "Belarus",
                              "Belgium",
                              "Belize",
                              "Benin",
                              "Bermuda",
                              "Bhutan",
                              "Bolivia",
                       
                              "Botswana",
                              "Bouvet Island",
                              "Brazil",
                           
                              "Bulgaria",
                              "Burkina Faso",
                              "Burundi",
                              "Cambodia",
                              "Cameroon",
                              "Canada",
                              "Cape Verde",
                        
                              "Chad",
                              "Chile",
                              "China",
                         
                              "Colombia",
                              "Comoros",
                              "Congo",
                              
                              "Cook Islands",
                              "Costa Rica",
                              "Cote D'Ivoire",
                              "Croatia",
                              "Cuba",
                              "Cyprus",
                              "Czech Republic",
                              "Denmark",
                              "Djibouti",
                              "Dominica",
                             
                              "Ecuador",
                              "Egypt",
                              "El Salvador",
                              "Equatorial Guinea",
                              "Eritrea",
                              "Estonia",
                              "Ethiopia",
                              
                              "Faroe Islands",
                              "Fiji",
                              "Finland",
                              "France",
                              "French Guiana",
                              "French Polynesia",
                              
                              "Gabon",
                              "Gambia",
                              "Georgia",
                              "Germany",
                              "Ghana",
                              "Gibraltar",
                              "Greece",
                              "Greenland",
                              "Grenada",
                              "Guadeloupe",
                              "Guam",
                              "Guatemala",
                              "Guinea",
                              "Guinea-Bissau",
                              "Guyana",
                              "Haiti",
                              
                              "Honduras",
                              "Hong Kong",
                              "Hungary",
                              "Iceland",
                              "India",
                              "Indonesia",
                              
                              "Iraq",
                              "Ireland",
                              "Israel",
                              "Italy",
                              "Jamaica",
                              "Japan",
                              "Jordan",
                              "Kazakhstan",
                              "Kenya",
                              "Kiribati",
                              
                              "Kuwait",
                              "Kyrgyzstan",
                             
                              "Latvia",
                              "Lebanon",
                              "Lesotho",
                              "Liberia",
                              
                              "Liechtenstein",
                              "Lithuania",
                              "Luxembourg",
                              "Macao",
                             
                              "Madagascar",
                              "Malawi",
                              "Malaysia",
                              "Maldives",
                              "Mali",
                              "Malta",
                              
                              "Martinique",
                              "Mauritania",
                              "Mauritius",
                              "Mayotte",
                              "Mexico",
                              
                              "Monaco",
                              "Mongolia",
                              "Montserrat",
                              "Morocco",
                              "Mozambique",
                              "Myanmar",
                              "Namibia",
                              "Nauru",
                              "Nepal",
                              "Netherlands",
                              
                              "New Caledonia",
                              "New Zealand",
                              "Nicaragua",
                              "Niger",
                              "Nigeria",
                              "Niue",
                              
                              "Norway",
                              "Oman",
                              "Pakistan",
                              "Palau",
                              
                              "Panama",
                              "Papua New Guinea",
                              "Paraguay",
                              "Peru",
                              "Philippines",
                              "Pitcairn",
                              "Poland",
                              "Portugal",
                              "Puerto Rico",
                              "Qatar",
                              "Reunion",
                              "Romania",
                              "Russian Federation",
                              "Rwanda",
                              "Saint Helena",
                              
                              "Saint Lucia",
                              
                              "Saint Vincent and the Grenadines",
                              "Samoa",
                              "San Marino",
                              
                              "Saudi Arabia",
                              "Senegal",
                              
                              "Seychelles",
                              "Sierra Leone",
                              "Singapore",
                              "Slovakia",
                              "Slovenia",
                              "Solomon Islands",
                              "Somalia",
                              "South Africa",
                              
                              "Spain",
                              "Sri Lanka",
                              "Sudan",
                              "Suriname",
                         
                              "Swaziland",
                              "Sweden",
                              
                              "Thailand",
                              "Timor-Leste",
                              "Togo",
                              "Tokelau",
                              "Tonga",
                         
                              "Tunisia",
                              "Turkey",
                              "Turkmenistan",
                           
                              "Tuvalu",
                              "Uganda",
                              "Ukraine",
                         
                              "United Kingdom",
                              "United States",
                            
                              "Uruguay",
                              "Uzbekistan",
                              "Vanuatu",
                              "Venezuela",
                              "Viet Nam",
                        
                              "Wallis and Futuna",
                              "Western Sahara",
                              "Yemen",
                              "Zambia",
                              "Zimbabwe"]
}
